# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Grayson Morris
title: Junior IT Support Specialist
email: grayson.r.morris@gmail.com
website: graysonmorris.tech

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: graysonmorris31
github_username:  graysonmor31
instagram_username: graysonmorris01_
twitter_username: graysonmorris31

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I recently graduated from Colorado State University with a BSc in Computer Science, but my passion for computing started long before that. As early as middle school, I had a habit of taking things apart just to see 
  how they worked. I wanted to understand everything about electrical systems, even if it meant breaking a few small appliances along the way. Eventually, I channeled that curiosity into something more constructive—building 
  my first computer during my freshman year of high school.

  From that moment on, I was hooked. Computers, to most people, were just another tool or even pure magic, but I wanted to know more. Unfortunately, my high school didn’t offer computer science classes, so I turned to 
  engineering as the next best thing. I loved math and physics, and since engineers worked with computers daily, how different could it be? As it turned out, very different. I quickly realized engineering wasn’t for me 
  and found myself at a crossroads—stay in a field that didn’t excite me or switch to something else.

  After some research, I discovered CSU’s Computer Information Systems (CIS) program, which blended business and computer science. It seemed like a practical choice, so I gave it a shot. However, after one semester, I realized 
  the business side didn’t interest me, and the computer science courses barely scratched the surface of what I wanted to learn.

  That summer, I had the opportunity to shadow family members working in cybersecurity. Seeing their work firsthand made everything click—I knew exactly what I wanted to do. I switched my major to Computer Science with a 
  concentration in Networks & Security, and I never looked back.

  With my new focus, I fully embraced learning. Programming, problem-solving, hardware, software, networking, security principles—I absorbed everything I could. I landed a job at CSU’s IT department, where I gained hands-on 
  experience troubleshooting systems, configuring networks, building workstations, and even leading training sessions for non-IT departments. This role gave me exposure to different IT teams and strengthened my technical and 
  communication skills.

  In my senior year, I took my experience a step further by interning at Woodward, Inc. as an IT Cybersecurity Intern. Initially, I worked with SIEM tools and monitoring systems, which introduced me to a new side of IT—Operational 
  Technology (OT) in a manufacturing environment. IT security in this space was entirely different from traditional enterprise IT, and learning about its unique challenges was eye-opening.

  Later in my internship, I shifted toward compliance and risk management, where I tested AI-driven compliance management tools and conducted third-party risk assessments. I loved this work because it allowed me to collaborate with 
  diverse teams while gaining a deeper understanding of security frameworks and governance.

  Now, I’m looking for a full-time role in <mark>IT or Cybersecurity</mark>, where I can apply my skills, continue learning, and contribute to a team that values security, efficiency, and innovation.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        caption: 2020 - 2024
        sub_title: BSc Computer Science
        quote: >
          The main function of education is to teach one to think sensibly and critically. It is not about acquiring knowledge, but about fostering the ability to think, question, and understand. Intelligence combined with character - that is the ultimate goal of a true education. - Alan Turing
        description: | # this will include new lines to allow paragraphs
          During my time at CSU, I gained a solid foundation in computer science. My coursework covered a wide range of topics, including general programming and OOP's principles, data structures and algorithms,
          large scale software development, and electives in web development and ethical computing practices.

          On top of that my concentration in <mark>Networks & Security</mark> gave me a deeper understanding of network protocols, security principles, and hands-on experience with network administration and cybersecurity tools.
          I learned many skills including safe programming practices, secure network design, network protocols, cryptography, and secure system configuration.
      - layout: left
        title: CompTIA
        caption: 2025
        sub_title: Security+
        description: | # this will include new lines to allow paragraphs
          I am currently taking a prep course for the Security+ certification. The course covers a wide range of topics including security controls, risk management, network security, IAM, cryptography, operational security,
          compliance, resilience, and incident response. This course builds on my prior knowledge from college and will help me prepare for a career in cybersecurity. I plan to take the exam in April.
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        link: colostate.edu
        sub_title: IT Support Specialist
        caption: May 2023 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
          - C++
          - C#
          - Python
          - PowerShell
          - Bash

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
