# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Grayson Morris
title: Junior IT Support Specialist
email: grayson.r.morris@gmail.com
website: graysonmorris.tech
phone: 719-237-6867
location: Fort Collins, CO

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  graysonmor31
linkedin_username: graysonmorris31
twitter_username: graysonmor31
instagram_username: graysonmorris01

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

I recently graduated from Colorado State University with a BSc in Computer Science, however my passion for computing started way before that. Starting about middle school I had a "hobby" of taking things apart. I wanted to know everything about how anything electrical worked.
After breaking one too many small appliances I focused my efforts in a more constructive direction, and built my first computer my freshman year of high school. I was hooked, getting to know these systems that to most just seemed like just another tool or were pure magic to others
fascinated me. I wanted to know more and more, but unfortunately my high school didn't really offer any computer science classes, so I decided engineering was the next best thing, I loved math and physics and I got to use computers everyday so how different could it be? Well I found
out pretty quickly it was very different and I actually didn't love doing engineering, by my first year of college I found myself stuck at a crossroads. Stay in engineering and be somewhat miserable for the foreseeable future or switch to something else. I did some research and found
that CSU offered a CIS program, that was a mix of business and computer science, "that would be good, practical business skills and computers im sold" I convinced myself, but that only lasted a semester, the business classes bored me and the computer classes were surface level at best. 

The following summer I was talking with some family members who worked in the cybersecurity sector and even shadowed them at their jobs a few times. After that I knew exactly what I wanted to do. I switched to computer science and never looked back. I knew my future was in IT and cyberseurity. I began to ataully enjoy 
my classes learning to code and effectively problem solve. Learning the ins and outs of hardware, software, networking, and security principles. I was like a sponge. I was able to get a job at the IT department at the student center at CSU and I loved it. I got to handle and troubleshoot a myriad of problems and learn more and more 
about the systems I was working on. I got to know different IT teams and got to do some work configuring the network, or building systems, or offering trainings to different departments outside of IT. Then my senior year I got the oppurtunity to intern for Woodward, Inc. as an IT Cybersecurity intern. I started working mostly with SIEM
and monitoring systems. This was a whole new world to me, I thought I Knew IT inside and out, but manufacturing was its own beast. There was the IT side I was used to but also the OT side which was new to me. This was a good thing though I was exposure and a learning oppurtunity. Eventually I moved more to the compliance side of
IT security where I spent most of my time trialing new AI complaince management systems and conducting third party risk assessments. I loved it, I got to work with a lot of different people and learn a lot of new things. I am now looking for a full time position in IT and/or cybersecurity where I can continue to learn and grow and offer
my skills to a new team.

# Skills Section

skills:
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        content:
          - C++
          - C#
          - Python
          - Java
          - Scala
          - SQL
          - Bash
          - Powershell
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/garysonmor31/homelab
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        link: it.colostate.edu
        sub_title: IT Support Specialist
        caption: May 2023 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Woodward, Inc. 
        link: woodward.com
        sub_title: Cybersecurity Intern
        caption: May 2024 - December 2024
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        caption: 2020 - 2024
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Colorado State I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and cybersecurity some of my other interests and hobbies are:
      - Snowboarding
      - Hiking
      - Tinkering with computers
      - Gaming
      - Reading

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag